import web
import os
import model.user as user
import model.helper as helper
from threading import Timer

urls = (
	'/', 'index',
	'/user(?:/(.*))?', 'userRequest',
	#TODO: add mongs like db browser, with option to only return json (read only?) (restricted - not able to read user collection)
	#TODO: add a last resort url handler that searches through static and returns what matches or 404s out
	'/(.*)', 'static',
)
app = web.application(urls, globals())


def cron():
	"""handles simple cron-like jobs such as rescraping"""
	print "cron jobs can be put here"
	t = Timer(10000, cron)
	t.start()

cron()


def loadhook():
	"""loadhook for setting contextual vars"""
	web.ctx.user = user.instance()
	web.ctx.dev = (web.input(dev='False').dev == 'True')  # if ?dev=True then dev will be set to True, otherwise it defaults to False

	inputs = web.input(username='', token='')
	#only run user.check if username and token are defined... still allow use of default guest account
	if inputs.username != '' and inputs.token != '':
		#try:
		web.ctx.user.check(username=inputs.username, token=inputs.token)  # validate user token if username and token are supplied
		#except:
		#	errorHandler()

app.add_processor(web.loadhook(loadhook))


def unloadhook():
	web.ctx.user.save()  # save incase any changes have been made to user

app.add_processor(web.unloadhook(unloadhook))


class index:
	def GET(self):
		return "<html><head><title>CSD</title></head><body>put docs generated by sphinx here</body></html>"


class userRequest:
	def GET(self, name=''):
		""" handles requests for user data, logins, and signups """
		if name == None or name == '':
			return helper.json_dump(web.ctx.user.safeData())
		elif name == 'login':
			#CONSIDER: add a delay to prevent excessive attempts

			inputs = web.input(username='', email='', password='')
			try:
				web.ctx.user.login(username=inputs.username, email=inputs.email, password=inputs.password)
			except Exception as error:
				return helper.error_dump(error)

			return helper.json_dump({'token': web.ctx.user.data['session']['token']})
		else:
			return web.application.notfound(app)  # this means it is not one of the defined meathods for interacting w/ the server


class static:
	def GET(self, filename):
		"""
			searches for and returns a requested static file
			this allows files in /static to be accessed as if they were in /
		"""
		try:
			return open(os.path.dirname(__file__) + '/static/' + filename, 'r').read()
		except:
			web.application.notfound(app)  # file not found


if __name__ == "__main__":
	app.run()
